// <auto-generated />
using System;
using Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Persistencia.Migraciones
{
    [DbContext(typeof(aplicationDbContext))]
    [Migration("20240221211204_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aplicacion.Dominio.Categories", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Publicationsid")
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("price")
                        .HasColumnType("float");

                    b.Property<int>("stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Publicationsid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Publications", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Storeid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("visibility")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("id");

                    b.HasIndex("Storeid");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Seller", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long>("CUIT")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("Storeid")
                        .HasColumnType("char(36)");

                    b.Property<string>("direction")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.HasIndex("Storeid");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            id = new Guid("e9545e97-f2ed-4dc7-ab52-116ca3043d58"),
                            CUIT = 20463633836L,
                            direction = "Av San Juan",
                            lastname = "Salinas",
                            name = "Franco"
                        },
                        new
                        {
                            id = new Guid("8c3063b7-be06-46c5-a7c2-a777d2bbbfbd"),
                            CUIT = 22993949399L,
                            direction = "Lanus",
                            lastname = "Mansilla",
                            name = "Facundo"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Store", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            id = new Guid("9b37a0c5-cc5b-4fe3-b064-79e4ffcaf3f9"),
                            name = "Nike"
                        },
                        new
                        {
                            id = new Guid("1b548119-5778-42c0-a509-b573e01d2a3a"),
                            name = "Adidas"
                        },
                        new
                        {
                            id = new Guid("fc63454c-21da-45b6-9543-c2f4e0107ed9"),
                            name = "Puma"
                        });
                });

            modelBuilder.Entity("Aplicacion.Dominio.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("Sellerid")
                        .HasColumnType("char(36)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Sellerid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Categories", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Product", null)
                        .WithMany("Category")
                        .HasForeignKey("ProductId");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Product", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Publications", null)
                        .WithMany("products")
                        .HasForeignKey("Publicationsid");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Publications", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Store", null)
                        .WithMany("publications")
                        .HasForeignKey("Storeid");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Seller", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Store", null)
                        .WithMany("sellers")
                        .HasForeignKey("Storeid");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Users", b =>
                {
                    b.HasOne("Aplicacion.Dominio.Seller", null)
                        .WithMany("user")
                        .HasForeignKey("Sellerid");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Product", b =>
                {
                    b.Navigation("Category");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Publications", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Seller", b =>
                {
                    b.Navigation("user");
                });

            modelBuilder.Entity("Aplicacion.Dominio.Store", b =>
                {
                    b.Navigation("publications");

                    b.Navigation("sellers");
                });
#pragma warning restore 612, 618
        }
    }
}
